project:
  type: book

book:
  title: "NEON Ecological Forecasting Challenge"
  author: "Ecological Forecasting Initative Research Coordination Network"
  date: now
  chapters:
    - index.qmd
    - Aquatics.qmd
    - Terrestrial.qmd
    - Ticks.qmd
    - Phenology.qmd
    - Beetles.qmd
    - Evaluation.qmd
    - Shared-Forecast-Drivers.qmd
    - UseInCourse.qmd
    - FAQ.qmd
  appendices:
    - WorkflowExample.qmd
    - container.qmd
  sidebar:
    logo: images/EFI_Logo-1.jpg
    search: true
bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

